### PR TITLE
Pubmed query and gene name search

### PR DESCRIPTION
**Pull request by lucylw**

### CODE REVIEW

**Comment by lucylw** [comment]
@agnesbao 
PubmedQuery class needs to be refactored before merging:

```get_ncbi_docsum''' looks to be the same function from ```geo_data.py''', there's no need to copy it into a new class. I deleted it from pubmed.py, and added the query_text as an input variable.

I also just added some comments to ```construct_query_term''' to clarify what it does. I'm not sure how this function is intended to be used. I'm assuming the order of operations is:

1. Get clusters of gene names from pvclust
2. Call construct_query_terms with the gene_name_list of each cluster to get a list of pubmed query terms
3. Use get_ncbi_docsum to retrieve the pubmed matches for each cluster
4. Parse abstracts as usual and generate wordclouds for each cluster

Can you clarify how the ```construct_query_term''' function fits into the pipeline? i.e., what does it need as input, what does it output, and where should it be called.

**Comment by agnesbao** [comment]
> @agnesbao
> PubmedQuery class needs to be refactored before merging:
> 
> `get_ncbi_docsum''' looks to be the same function from`geo_data.py''', there's no need to copy it into a new class. I deleted it from pubmed.py, and added the query_text as an input variable.
> 
> I also just added some comments to ```construct_query_term''' to clarify what it does. I'm not sure how this function is intended to be used. I'm assuming the order of operations is:
> 
> 1. Get clusters of gene names from pvclust
> 2. Call construct_query_terms with the gene_name_list of each cluster to get a list of pubmed query terms
> 3. Use get_ncbi_docsum to retrieve the pubmed matches for each cluster
> 4. Parse abstracts as usual and generate wordclouds for each cluster
> 
> Can you clarify how the ```construct_query_term''' function fits into the pipeline? i.e., what does it need as input, what does it output, and where should it be called.

First of all, I don't know if I did it wrong by doing a `git rebase master` on my side, but I'm not seeing the change you mentioned. Hope I didn't screw up your change.

The `construct_query_term` takes gene names (list) from a cluster, and outputs a list of query_terms. Because each query term has character limit of 4000, so need to loop through the query_term to retrieve all pubmed search for one cluster. Basically your description of the process is accurate!

**Comment by lucylw** [comment]
Okay, I think I understand and tried to incorporate. The two groups for psoriasis wound up with 5828 and 10431 pubmed articles respectively. This is taking the cluster to GDS mappings, and mapping each GDS to its genes (from gds_dict). 

My questions is (@agnesbao, @rbutleriii, @yingeddi2008, @subhajit06, please chime in), do we want to do this? The pubmed abstract retrieval alone will take several hours for each cluster at this many articles. We could filter the genes for more or less important ones to reduce the number of pubmed articles that come up in search. Thoughts?

**Comment by lucylw** [comment]
Another separate thing, @agnesbao, The get_term_frequencies function occasionally throws an error:
AttributeError: 'DictionaryElement' object has no attribute 'count'. Could you look into this?

**Comment by rbutleriii** [comment]
@lucylw, when it is retrieving genes from gds_dict, is that all genes in each gds, or only the up/down ones? I thought there was a separate geo_dict? I will look it over today and refresh my memory.

Is it taking hours now? The abstract retrieval should be pretty quick even with 15k. You can fetch 50k full xml records from clinvar in about 5 minutes. The word scraping might take longer though.

**Pull request merged**
